### ISSUE TITLE
Question about images_e encoder output

### ISSUE THREAD

**Issue by TrybusRafalJan** [A03ki/f-AnoGAN#10]
Hello A03ki, thank you for your amazing code here. It is helping me a lot in my university project. I'm trying to understand it and follow your work. 
If you don't mind answering my short question i.e. what is the interpretation of the images saved in "images_e" folder. The ones that are the output of "train_z_encoding_izif.py"? At the first glance they look just like the ones straight from the GAN part in "f-AnoGAN/mvtec_ad/results/images". Could you please explain what is the difference.

**Comment by A03ki** [comment]
Hello @TrybusRafalJan, thank you for asking the question. I'm glad I could help your university project.

> If you don't mind answering my short question i.e. what is the interpretation of the images saved in "images_e" folder. The ones that are the output of "train_z_encoding_izif.py"?

Yes,  the images saved in "images_e" folder are the output of "train_z_encoding_izif.py".

> At the first glance they look just like the ones straight from the GAN part in "f-AnoGAN/mvtec_ad/results/images". Could you please explain what is the difference.

If the images in "results/images_e" folder are close to the images in "results/images" folder, you can be sure that the encoder is learning correctly. (In "train_z_encoding_izif.py", the encoder is learning to generate fake latent variables.)

**Comment by TrybusRafalJan** [comment]
Hello @A03ki,
Thank you for your kind response. I do understand it now. I will try to implement inference function to your solution, I may share it with you, if you'd be interested.

 All the best to you :)
