### ISSUE TITLE
python setup.py install

### ISSUE THREAD

**Issue by qiuchun** [A03ki/f-AnoGAN#13]
when i run python setup.py install , it only used in cpu not GPU  ，Does it support compiling under GPU？

**Comment by A03ki** [comment]
Hi, @qiuchun.

Sorry, `python setup.py install` doesn't support GPU.
However, `python train_wgangp.py` and `train_encoder_izif.py` support  GPU.

**Comment by qiuchun** [comment]
think you  i solve this problem   now  i can  use GPU to run train_wgangp.py and train_encoder_izif.py.
 i want to know when i runed  the step 4 ,this mode's  result is what?

**Comment by A03ki** [comment]
If the training step goes well, the portions not included in the training data are displayed as a difference.
Incidentally, this image is in "results/images_diff".
