### ISSUE TITLE
Huge generator and tiny discriminator?

### ISSUE THREAD

**Issue by Zephyr69** [A03ki/f-AnoGAN#15]
I'm training these models with my own dataset at --latent_dim 1000 and --image_size 320, and I notice that the saved generator is about 3gb while the discriminator is around 500kb. Should I scale up the discriminator?

**Comment by A03ki** [comment]
Hi, @Zephyr69.
Thanks for using this repository.

It is difficult to judge from your information alone. In your configuration, is image generation not working?

**Comment by Zephyr69** [comment]
> Hi, @Zephyr69. Thanks for using this repository.
> 
> It is difficult to judge from your information alone. In your configuration, is image generation not working?

Thanks for your reply! I'm looking to detect very small anomalies (~7x7) on a relatively big image (~1000x1000).

The image reconstruction is working with --latent_dim 100, but the image quality isn't good enough to perform the task. The G_loss quickly becomes all negative, idk if it's expected? Like this:
[Epoch   0/450] [Batch 0/2] [D loss: 9.225899] [G loss: 0.002858]
[Epoch   1/450] [Batch 0/2] [D loss: 8.284700] [G loss: 0.007262]
[Epoch   2/450] [Batch 0/2] [D loss: 5.510290] [G loss: -0.023316]
[Epoch   3/450] [Batch 0/2] [D loss: -4.197353] [G loss: -0.223050]
[Epoch   4/450] [Batch 0/2] [D loss: -32.129951] [G loss: -2.417758]
[Epoch   5/450] [Batch 0/2] [D loss: -88.610680] [G loss: 9.614916]
[Epoch   6/450] [Batch 0/2] [D loss: -126.860847] [G loss: 17.268265]
[Epoch   7/450] [Batch 0/2] [D loss: -106.419914] [G loss: -2.722338]
[Epoch   8/450] [Batch 0/2] [D loss: -115.030739] [G loss: -57.363503]
[Epoch   9/450] [Batch 0/2] [D loss: -0.776878] [G loss: -69.117149]
[Epoch  10/450] [Batch 0/2] [D loss: -19.475677] [G loss: -83.537827]
[Epoch  11/450] [Batch 0/2] [D loss: -303.673645] [G loss: 167.087326]
[Epoch  12/450] [Batch 0/2] [D loss: -146.033997] [G loss: -121.324600]
...

Increasing --latent_dim to 1000 will make image reconstruction fail; the generator won't produce any meaningful image.

**Comment by A03ki** [comment]
@Zephyr69
I'm sorry for the late reply.

That task may be difficult with the current implementation.
The implemented GAN's structure are not suitable for generating large images.
Please consider forking this repository and modifying the GAN's structure.
