### ISSUE TITLE
G_loss and D_loss are negative numbers when running train_wgangp.py using my own image dataset

### ISSUE THREAD

**Issue by nene211** [A03ki/f-AnoGAN#17]
Hi,@A03ki.
     Thank you very much for your code! When I use my own image dataset to train the WGAN, both of its G_loss and D_loss are negative nmbers, I wonder if this situation is right? And Im not really understand what the class mean, for example, I have 100 normal images and 100 ano images, so I put 100 normal images in the path "your own dataset-dataset-train-class0", and put the 100 ano images in the path"your own dataset-dataset-test-class0", then I run wgangp.py, izif.py, detection.py and save.py one by one? Is this correct?
     Thank you again for your code and your answer.

**Comment by nene211** [comment]
and the size of  my pictures are all 64*64, so...is something wrong in my dataset?

**Comment by nene211** [comment]
well i finished all codes and get the image results, but how can i get the pr-auc and roc-auc picture? and what the 'h' mean in the fourth picture?

**Comment by nene211** [comment]
well...i get a high accurary, the only problem is the loss...

**Comment by A03ki** [comment]
Hi, @nene211.
Thank you for using this repository.
I see you have a few questions, so I'll answer them in order.

> When I use my own image dataset to train the WGAN, both of its G_loss and D_loss are negative numbers, I wonder if this situation is right?

Taking negative values is not necessarily a false result. Please check the two losses continue to change stably. (It may be hard work to check the fluctuation of the two losses in this repository.)

>  And Im not really understand what the class mean, for example, I have 100 normal images and 100 ano images, so I put 100 normal images in the path "your own dataset-dataset-train-class0", and put the 100 ano images in the path"your own dataset-dataset-test-class0", then I run wgangp.py, izif.py, detection.py and save.py one by one?

Yes! You can get the training and test results by executing the following commands in order.
```bash
python train_wgangp.py "your own dataset-dataset-train-class0"
python train_encoder_izif.py "your own dataset-dataset-train-class0"
python test_anomaly_detection.py "your own dataset-dataset-train-class0"
python save_compared_images.py "your own dataset-dataset-train-class0" --n_iters 0 --n_grid_lines 10
```

> and the size of my pictures are all 64*64, so...is something wrong in my dataset?

That image size is fine.


I hope that answers your questions.

**Comment by nene211** [comment]
thank you so much! It runs well on my image dataset and the accuracy is high! Thank you!!!

**Comment by nene211** [comment]
Well I have another question now...@A03ki
I want to know that if my image  is not 64*64, should i change some parameters of the model? Or i just put my images in the train/test folders and run without changing anyting of the codes?

**Comment by A03ki** [comment]
Hi, @nene211. Thank you for your question.
That's correct. If your image is not 64×64, it will be automatically resized to the default value (64×64).

**Comment by nene211** [comment]
OkOk，thank you again for your excellent codes and answers, you really help me a lot!
