### ISSUE TITLE
Graph values is off.

### ISSUE THREAD

**Issue by jonolo-3** [A03ki/f-AnoGAN#7]
Hi!
I have tried your code on a custom dataset and got some bad values for my graphs, so I tested the MvTec Carpet class as well and got similar bad results... Do you happen to know what might cause this?
![roc-auc](https://user-images.githubusercontent.com/11312387/100237852-c4ffd100-2f2f-11eb-8cd9-ec86d0de1017.png)
![pr-auc](https://user-images.githubusercontent.com/11312387/100237857-c6c99480-2f2f-11eb-8030-e2dea37cf07a.png)

**Comment by ranchenhao** [comment]
Hi! I also tried on MvTec Bottle and got similar bad results. Have you solved this?

**Comment by A03ki** [comment]
I'm sorry for the delay in replying to @jonolo-3 and @ranchenhao.

I believe that the ability to reconstruct images cleanly is necessary for correct anomaly detection.
However, we used a simple GAN, which has the poor ability to reconstruct images.
Thus, I think that we fail to produce results.

**Comment by exchoco** [comment]
is this because of the structure of the network differ from the original implementation?

**Comment by A03ki** [comment]
@exchoco 
Yes. I think the AUC can be improved by using official ResNet-based GAN or other sophisticated GANs.
