### ISSUE TITLE
I want to train this f-anoGAN networks with my image datasets.

### ISSUE THREAD

**Issue by bemoregt** [A03ki/f-AnoGAN#8]
HI, @A03ki 

I want to train this f-anoGAN networks with my image datasets.

But , I don't know the minimal data structure for train.

Like the mvtec-ad datasets, it also must have the mask image?

I wonder ~

Thanks in advance.
Best,
@bemoregt.

**Comment by A03ki** [comment]
HI, @bemoregt

Thanks for your comment.

I improved my project so that you can use your own dataset.
See [README.md](https://github.com/A03ki/f-AnoGAN) how to use it.

I hope your project goes well.
